# import = [
#     "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
# ]

[env]
term = "xterm-256color"

[window]
padding.x = 6
padding.y = 6

decorations = "None"
startup_mode = "Fullscreen"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13

[shell]
program = "/bin/zsh"
args = ["-l"]
